# Generated by Django 3.1.1 on 2020-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity_left',
            field=models.IntegerField(default=0),
        ),
    ]
