# Generated by Django 3.1.1 on 2020-09-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20201001_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='PLACED', max_length=50),
        ),
    ]
